#!/bin/sh
# ----------------------------------------------------------------------------
#
#  (c) Copyright 2001-2017 NewNet                 
# 
#  This software is proprietary to and embodies the confidential technology 
#  of NewNet. Possession, use, duplication or dissemination of the 
#  software and media is authorized only pursuant to a valid written license 
#  from NewNet.
#
# ----------------------------------------------------------------------------
# $Id: pre_remove,v 1.3 2017/06/30 09:06:49 fkok Exp $
# ----------------------------------------------------------------------------
#

# set variables
if [ -z $INSTDIR ]
then
    echo "ERROR: INSTALLDIR not specified!"
    exit 1;
fi

INSTALLDIR=$INSTDIR
OURVARDIR='/var/Automate'

rm -f $OURVARDIR/pkg/OS/any
rm -f $OURVARDIR/pkg/OS/fallback

##
# Remove the init scripts on package removal (not on upgrade)
#
# activate the init script
if [ -r /etc/tekelec.cfg ];  then
    # TPD
    echo "TPD was never supported"
    exit 1
elif [ -x /usr/lib/lsb/remove_initd ]; then
    # Find our RHEL version
    maj_ver='6'     # Assume odl if not known
    if [ -f /etc/redhat-release ] ; then
        maj_ver="$(cat /etc/redhat-release | sed s/.*release\ // | cut -d'.' -f1)"
    fi
    if [ "$maj_ver" -le '6' ]; then # RHEL7 >= does not need initd
        /usr/lib/lsb/remove_initd /etc/init.d/zz-Automate
        /usr/lib/lsb/remove_initd /etc/init.d/automate_update
        /usr/lib/lsb/remove_initd /etc/init.d/automate_kernel_patch
    else
        systemctl --quiet disable automate.service
        systemctl --quiet disable automate_update.service
    fi
else
    # Solaris
    rm -f  /etc/rc3.d/S99zz-Automate
    rm -f  /etc/rc1.d/S99automate_kernel_patch
    rm -f  /etc/rc3.d/S98automate_update
fi

# Remove our link if still there as post_install create them
rm -f /etc/init.d/zz-Automate
rm -f /etc/init.d/automate_kernel_patch
